services:
  mongo:
    image: mongo:6
    container_name: reservation-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=reservation
      - MONGO_LOG_LEVEL=warning
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - reservation-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: william20220828/reservation-platform-backend:2025.09.15
    container_name: reservation-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://reservation-mongo:27017/reservation
      - JWT_SECRET=my_jwt_secret
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - reservation-net

  frontend-builder:
    image: william20220828/reservation-platform-frontend-builder:2025.09.15
    container_name: reservation-frontend-builder
    volumes:
      - frontend-dist:/app/dist
    networks:
      - reservation-net
    restart: "no"
    command: "true" 

  nginx:   
    image: william20220828/reservation-platform-nginx:2025.09.15
    container_name: reservation-nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend-builder
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro  
    ports:
      - "80:80"
    networks:
      - reservation-net

volumes:
  mongo-data:
  frontend-dist:

networks:
  reservation-net:
    driver: bridge           